/*
Navicat MySQL Data Transfer

Source Server         : localhost
Source Server Version : 50623
Source Host           : localhost:3306
Source Database       : laravel-blog

Target Server Type    : MYSQL
Target Server Version : 50623
File Encoding         : 65001

Date: 2016-09-08 19:30:01
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for migrations
-- ----------------------------
DROP TABLE IF EXISTS `migrations`;
CREATE TABLE `migrations` (
  `migration` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `batch` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- ----------------------------
-- Records of migrations
-- ----------------------------
INSERT INTO `migrations` VALUES ('2014_10_12_000000_create_users_table', '1');
INSERT INTO `migrations` VALUES ('2014_10_12_100000_create_password_resets_table', '1');
INSERT INTO `migrations` VALUES ('2016_09_07_105516_create_posts_table', '2');

-- ----------------------------
-- Table structure for password_resets
-- ----------------------------
DROP TABLE IF EXISTS `password_resets`;
CREATE TABLE `password_resets` (
  `email` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `token` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  KEY `password_resets_email_index` (`email`),
  KEY `password_resets_token_index` (`token`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- ----------------------------
-- Records of password_resets
-- ----------------------------

-- ----------------------------
-- Table structure for posts
-- ----------------------------
DROP TABLE IF EXISTS `posts`;
CREATE TABLE `posts` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `slug` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `title` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `content` text COLLATE utf8_unicode_ci NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `updated_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `published_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`id`),
  UNIQUE KEY `posts_slug_unique` (`slug`),
  KEY `posts_published_at_index` (`published_at`)
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- ----------------------------
-- Records of posts
-- ----------------------------
INSERT INTO `posts` VALUES ('1', 'consectetur-reiciendis-pariatur-aut', 'Consectetur reiciendis pariatur aut.', 'Consequatur quis et dolores tempora ut qui exercitationem quasi. Et temporibus esse dolorem. Nihil libero non aut optio fugiat.\n\nDebitis quod at voluptatum aspernatur ratione nemo. Dolorum dolores veniam nobis.\n\nQuia dolorem ut quibusdam quo soluta ipsa voluptatem. In reprehenderit sit veritatis itaque. Accusantium assumenda corrupti possimus quia nostrum perferendis nihil.\n\nPraesentium harum dicta dolor dolorem. Assumenda quidem iusto alias et et. Necessitatibus autem velit aut voluptatum.\n\nDolorem ratione molestias eveniet quos iusto. Possimus consequuntur magnam molestias soluta. Dicta facere quibusdam hic est.', '2016-09-07 11:09:31', '2016-09-07 11:09:31', '2016-08-16 01:14:52');
INSERT INTO `posts` VALUES ('2', 'sed-commodi-delectus-fugit-non-rerum', 'Sed commodi delectus fugit non rerum.', 'Labore ab quia corrupti reiciendis suscipit doloremque delectus. Laudantium ea at eos facere ut mollitia. Voluptatem vitae earum consectetur dolores.\n\nFuga debitis atque vero molestias possimus harum iure vero. Ea aut dolorum cumque temporibus in sed quisquam. Eos error architecto qui maxime consectetur incidunt explicabo.\n\nQuisquam qui qui animi eum. Fugiat perferendis aliquam veritatis corrupti suscipit nulla. Necessitatibus blanditiis est sequi. Officiis vel qui accusamus ratione voluptatum.\n\nImpedit praesentium nisi eius quia. Dolores molestiae rem quibusdam est debitis. Rem repudiandae et eius et occaecati quasi officia.\n\nAliquid laboriosam illum libero ipsum quibusdam ut. Est voluptatem distinctio ut id ullam mollitia. Fuga eius ea autem quis debitis dolore distinctio.\n\nDolores dolore dicta itaque molestiae tempora. Fugiat quae corrupti pariatur. Enim qui cupiditate quia unde omnis voluptatibus doloremque deleniti.', '2016-09-07 11:09:31', '2016-09-07 11:09:31', '2016-08-19 13:05:33');
INSERT INTO `posts` VALUES ('3', 'est-quasi-blanditiis-pariatur-aut-qui-et', 'Est quasi blanditiis pariatur aut qui et.', 'Voluptatum aut natus et. Dolores quidem quas autem aut alias aut voluptatibus. Neque sint tempora officiis. Soluta ipsam sint et aperiam iure placeat adipisci occaecati. A architecto doloribus quia in et accusamus est.\n\nConsequatur id minus rerum consequatur sit. Dolorum quis ad voluptas aut. Ut explicabo illum nemo quisquam ipsa atque quisquam.\n\nQui odio laborum eos facilis doloremque repellendus. Blanditiis quia sed repellat quia nam. Et deleniti id doloremque omnis molestiae. Dolor quod sed repellat veniam in minus eum.\n\nBeatae eum eius et ullam. Voluptatum minima adipisci ducimus voluptates dolor.\n\nEt nesciunt dolores ad deserunt voluptatem sint voluptatem. Ut sed accusantium veritatis. Est rerum omnis necessitatibus quisquam ea veritatis quasi. Eligendi sit eveniet ipsum libero et praesentium eum.', '2016-09-07 11:09:31', '2016-09-07 11:09:31', '2016-08-13 02:50:47');
INSERT INTO `posts` VALUES ('4', 'aut-sunt-voluptate-eos-reiciendis-illo-distinctio-qui', 'Aut sunt voluptate eos reiciendis illo distinctio qui.', 'Mollitia suscipit et repellendus. Est porro tenetur voluptatem dolorem deserunt saepe commodi.\n\nOccaecati ipsa quam sed cupiditate qui dolorum similique. Quis adipisci quidem est fugit deserunt veritatis molestias. Voluptatibus doloremque aut omnis dolorum nemo dolores.\n\nEos amet porro deserunt at ratione vel consequatur. Non commodi ab quis. Neque velit laboriosam laborum. Ut corrupti praesentium qui suscipit est quas est sed.', '2016-09-07 11:09:32', '2016-09-07 11:09:32', '2016-09-08 03:55:29');
INSERT INTO `posts` VALUES ('5', 'amet-minus-vitae-iste-amet-explicabo-maiores-molestiae-velit-dolorum', 'Amet minus vitae iste amet explicabo maiores molestiae velit dolorum.', 'Est voluptates officia nihil perspiciatis adipisci dicta. Occaecati beatae esse consequatur. Quasi eius quia sed qui. Dolorem est ad impedit perferendis quod omnis.\n\nDeleniti vel quo tenetur voluptate earum. Aspernatur magni at voluptatem recusandae quidem nulla dolore. Ipsa provident laboriosam aut in est pariatur quia. Fugiat ut quo natus incidunt deleniti sed distinctio ut. Dolorem corporis deserunt voluptatem enim est.\n\nQuasi impedit occaecati illo ut tenetur iure. Reprehenderit reprehenderit quia maiores natus. Facilis eius nihil sunt eum quaerat accusamus.', '2016-09-07 11:09:32', '2016-09-07 11:09:32', '2016-09-09 10:24:17');
INSERT INTO `posts` VALUES ('6', 'sunt-doloremque-earum-iste', 'Sunt doloremque earum iste.', 'A quia nisi tempore harum rerum. Quis qui quis vero aut et in possimus. Odit est deleniti deserunt fugiat molestias voluptas ut. Qui accusantium quas veritatis minus et. Totam eos officiis aliquam voluptatem velit.\n\nEum voluptatibus ut voluptatem similique sint delectus ut. Ipsa quia praesentium id pariatur est harum id recusandae. Consequatur atque sunt quibusdam nisi amet. Velit enim aut repellat nemo ea.\n\nCupiditate iusto nulla voluptas praesentium in. Officiis quam rem ea natus et impedit quisquam. Et numquam necessitatibus a error vitae autem.\n\nAd facere ab vel cumque optio saepe voluptas repudiandae. Sequi dolore voluptatem praesentium. Harum quis temporibus omnis deserunt. Ratione voluptatem ut odit fuga quos sint.', '2016-09-07 11:09:32', '2016-09-07 11:09:32', '2016-08-09 16:06:50');
INSERT INTO `posts` VALUES ('7', 'dolor-sunt-sit', 'Dolor sunt sit.', 'Ut eveniet et veritatis eos. Ut sit saepe rerum perspiciatis quis omnis. Dolor tempore fuga iure nihil commodi recusandae vel.\n\nVoluptatem et numquam modi modi. Voluptatum nihil laudantium et atque doloremque. Sint similique culpa voluptates dolorum sit amet illo facilis.\n\nAliquid optio soluta deleniti velit placeat cumque rerum. Dolores velit repellendus et et soluta ut. Eveniet rerum nobis et alias odit fugiat. Reiciendis aspernatur aperiam illum. Qui ducimus praesentium impedit sapiente.\n\nId voluptatem magnam accusantium dolores. Nihil aut officia unde error et quia ipsam. Rerum dolorem maiores est. Unde dolor dolorem qui explicabo omnis sed.\n\nIpsa quis praesentium mollitia quo nihil. Explicabo omnis eaque nam numquam. Minima autem consectetur qui est delectus. Et dolor illo quis reprehenderit nobis.', '2016-09-07 11:09:32', '2016-09-07 11:09:32', '2016-08-15 13:17:54');
INSERT INTO `posts` VALUES ('8', 'exercitationem-veniam-consectetur-vel-optio-qui-totam-et', 'Exercitationem veniam consectetur vel optio qui totam et.', 'Dignissimos autem corrupti dolore tempore sint accusamus. Ut rerum accusantium quia laudantium ipsum dolor nihil unde. Minus in voluptatum harum consequatur animi reprehenderit. Neque quidem nostrum sequi eligendi blanditiis.\n\nQui in vitae impedit sed quae aut cumque. Suscipit qui voluptas excepturi enim ad id id. Voluptatem ratione commodi aut.\n\nEarum laudantium consequatur deserunt et. Maxime corrupti ea et unde labore est. Repellendus voluptatem sint non et facilis distinctio. Aut asperiores eveniet et quaerat. Facilis doloremque excepturi tempore est.\n\nExercitationem id laboriosam cum expedita. Ipsam voluptate atque est ratione. Dolores at voluptatum est excepturi qui.\n\nDolor libero recusandae recusandae aut. Commodi illo consectetur ut. Minus error eligendi consequatur aut. At molestiae et eos omnis.\n\nMinus et pariatur repudiandae eveniet aperiam id. Voluptatum perspiciatis et est quo praesentium rerum aliquam. Atque unde quis animi ea sint.', '2016-09-07 11:09:32', '2016-09-07 11:09:32', '2016-08-11 04:18:08');
INSERT INTO `posts` VALUES ('9', 'aliquid-ea-error-nihil-at-adipisci-corrupti-iste-quaerat', 'Aliquid ea error nihil at adipisci corrupti iste quaerat.', 'Et dicta voluptas earum voluptatum laboriosam fugiat sunt. Libero in non ea delectus necessitatibus ab.\n\nQuis ea vel tempora inventore non doloremque quisquam. Occaecati esse ad excepturi ea id et esse. Neque nihil pariatur molestiae cumque dignissimos. Nemo totam et quia consequuntur ullam et laboriosam.\n\nDolor at magnam ut nulla atque non est. Saepe velit rerum voluptas fuga nostrum. Ratione illum ea delectus a. Error qui quod et repudiandae at quo autem. Enim corporis eaque dicta.\n\nInventore nostrum nihil esse eaque at unde. Voluptas veritatis magni eius ut enim. Aut ipsam molestiae repellendus eos. Dolorem id optio autem culpa.', '2016-09-07 11:09:32', '2016-09-07 11:09:32', '2016-08-23 20:48:50');
INSERT INTO `posts` VALUES ('10', 'mollitia-facilis-quis-cumque', 'Mollitia facilis quis cumque.', 'Autem incidunt totam ea alias distinctio consectetur. Est deserunt aliquid reprehenderit ullam. Quam pariatur earum repellendus voluptas est quidem culpa.\n\nVero ipsa culpa unde reprehenderit. Inventore sed ut perferendis dignissimos. Non quo est saepe ut. Corrupti porro non enim.\n\nBeatae quis accusamus illo aut qui dolor non. Molestiae voluptate velit minus possimus consequatur. Tempore dignissimos et voluptate sapiente.\n\nEt illum velit corrupti eos tempora laboriosam molestias. Quis necessitatibus ipsa deleniti aperiam. Numquam voluptas inventore sunt quia voluptas ex similique. Nam quaerat placeat modi et nihil reprehenderit. Soluta cupiditate possimus reiciendis voluptatum ipsa iste ducimus.', '2016-09-07 11:09:32', '2016-09-07 11:09:32', '2016-08-20 05:50:06');
INSERT INTO `posts` VALUES ('11', 'id-est-est-qui-saepe-voluptas-eos-vel', 'Id est est qui saepe voluptas eos vel.', 'Cumque et sunt maiores et quis aliquam dolore. Minima eius et similique delectus. Est alias sed quisquam hic aut sint.\n\nNesciunt quam aut rerum voluptatem consequatur voluptas. Enim eos voluptates sit mollitia repudiandae laborum nesciunt. Amet aut cupiditate architecto numquam culpa.\n\nSed velit earum culpa ea voluptatem molestias similique. Atque eos consequatur autem eos ducimus. Dignissimos qui et libero impedit provident.\n\nRem voluptas labore eum rem nisi voluptate ea nostrum. Consequatur nisi modi est et voluptatibus. Nesciunt et sint quo deserunt.\n\nSequi et dolores quos. Qui maxime doloribus a harum voluptatem qui. Repudiandae quia exercitationem quaerat quis quibusdam repellat. Recusandae eius culpa aspernatur.', '2016-09-07 11:09:32', '2016-09-07 11:09:32', '2016-08-16 13:23:23');
INSERT INTO `posts` VALUES ('12', 'molestiae-laboriosam-exercitationem-odit-sit-et', 'Molestiae laboriosam exercitationem odit sit et.', 'Voluptas doloribus natus laboriosam officiis. Id vero beatae aspernatur voluptatum dolorem reiciendis. Quo assumenda voluptatem perspiciatis. Et et rerum atque molestias.\n\nSed laborum dolore est voluptatem rem. Sit possimus aperiam aperiam officia cupiditate. Iusto ut id vel quos atque. Alias amet delectus sed temporibus perspiciatis error alias.\n\nIste eum commodi sapiente sequi doloribus. Nulla aperiam molestiae dolor nam odio minima. Rerum maiores veniam quia temporibus laudantium sed.\n\nEveniet placeat aliquam corrupti est quod unde corporis. Tenetur impedit maiores rem aut officia.\n\nPorro id asperiores consequuntur. Magni nesciunt omnis culpa sed iste a aspernatur cupiditate. Cum aut quas aut autem voluptas et.\n\nNostrum non voluptatem magni voluptas et maiores enim. Fuga dignissimos qui et illo ut voluptas. Officia porro et rerum dolorum dolores sed sed. Quas laborum veritatis et.', '2016-09-07 11:09:32', '2016-09-07 11:09:32', '2016-09-02 23:35:36');
INSERT INTO `posts` VALUES ('13', 'dolor-quo-amet-voluptatem-praesentium', 'Dolor quo amet voluptatem praesentium.', 'Et animi nesciunt porro porro molestias. Dolor nesciunt esse reiciendis aut. Ut aperiam delectus quam optio aspernatur quasi est. Facere dolore nemo impedit.\n\nVel ipsa ab et esse est qui. Voluptas vel inventore hic voluptas. Sed perspiciatis assumenda libero est quis. Eaque placeat aut sequi consequatur.\n\nQuo aut sint distinctio. Soluta id nam facere rem inventore consequatur vitae aut. Dolor consequatur tenetur natus labore sunt.\n\nNobis consectetur consequatur ea facere. Autem qui magni aperiam laudantium totam. Rerum tempore tempore non praesentium consequatur.\n\nOdit exercitationem quis cum rerum et est. Voluptatibus quia alias aut.\n\nDolorum praesentium vel autem molestiae. Unde quia dolorem earum. Quo quia facere quia similique eos.', '2016-09-07 11:09:32', '2016-09-07 11:09:32', '2016-08-28 23:58:11');
INSERT INTO `posts` VALUES ('14', 'aut-alias-et-reiciendis', 'Aut alias et reiciendis.', 'Maiores vero veritatis ut ut illum voluptas asperiores. Reprehenderit voluptatibus aut et ut. Quidem fuga illo explicabo a debitis.\n\nTempora consequuntur nostrum magnam. Velit earum at aut eum possimus quod voluptatem. Quasi perspiciatis adipisci in consequatur. Ut consequatur est ex error saepe. Alias aliquid rerum excepturi et.\n\nOfficiis non consectetur est sapiente velit soluta quo. Similique aut deserunt voluptatem voluptatem voluptatem est nostrum qui. A numquam labore debitis. Magnam rerum rerum explicabo enim sunt similique harum.\n\nHic voluptates blanditiis est rem. Nostrum dignissimos porro fugiat nesciunt ea odit quia libero. Soluta et officia vero numquam omnis. Voluptatem in molestias rerum blanditiis molestias nihil aut.', '2016-09-07 11:09:32', '2016-09-07 11:09:32', '2016-08-17 13:14:30');
INSERT INTO `posts` VALUES ('15', 'molestiae-distinctio-ea-necessitatibus-officia-sed', 'Molestiae distinctio ea necessitatibus officia sed.', 'Quia aut velit animi possimus eveniet similique. Eum et tenetur nam aut quo quis tenetur. Et quis eaque et quas voluptatem. Amet eveniet laudantium eaque voluptas sed quidem eos.\n\nRem ratione et rerum voluptas dolorum aut. Voluptas earum optio quas quia dolorem ratione quia. Similique eius aut eos totam.\n\nEnim dignissimos nemo aut rerum dignissimos dolorem. Repellat itaque ad tempore et. Quo ut quis quaerat ratione libero eius.', '2016-09-07 11:09:32', '2016-09-07 11:09:32', '2016-08-30 16:25:40');
INSERT INTO `posts` VALUES ('16', 'itaque-totam-quod', 'Itaque totam quod.', 'Quibusdam dicta rerum velit aperiam ut et sunt. Officiis reprehenderit odio est beatae. Inventore ut ea enim beatae velit fugit quibusdam. Ipsum temporibus neque corrupti accusantium sed. Dolores sapiente provident eius eum asperiores voluptatem reiciendis.\n\nExcepturi sit voluptatem dolores ea. Excepturi perspiciatis temporibus repellat consequatur sit praesentium facere. A excepturi sint ut itaque sed eos sunt. Veritatis voluptas et quos voluptatibus voluptas expedita.\n\nQuod voluptas voluptatem adipisci recusandae ipsa delectus dolorem. Itaque odit aut repellendus dolorem quam. Consequatur est dolor ut aut.\n\nCulpa inventore aut rerum hic. Magnam autem laboriosam quasi omnis in omnis. Consectetur rerum optio vitae quis consectetur. Veniam placeat perspiciatis et.', '2016-09-07 11:09:32', '2016-09-07 11:09:32', '2016-09-03 22:40:46');
INSERT INTO `posts` VALUES ('17', 'aut-optio-autem-deleniti-veniam-et-quisquam', 'Aut optio autem deleniti veniam et quisquam.', 'Incidunt saepe autem sit beatae numquam laborum. Cumque qui eos nihil molestias. Aut dolore iste voluptatem ab repellendus possimus ullam assumenda. Id et iste rerum.\n\nSimilique saepe impedit id voluptas mollitia molestias velit. Doloribus molestiae laborum omnis. Eum sit necessitatibus earum quo culpa non est.\n\nSit quibusdam animi quod dolorem ut. Sed ut dolores veniam. Et porro dolores ratione consequatur blanditiis. Ad quis omnis et repellat animi eos optio ullam.', '2016-09-07 11:09:32', '2016-09-07 11:09:32', '2016-08-09 16:55:00');
INSERT INTO `posts` VALUES ('18', 'at-dolores-error-quis', 'At dolores error quis.', 'Minus reprehenderit sapiente dolorum. Consequatur aliquam id eius dolor dolor adipisci. Tempore unde dolor occaecati officiis quasi. Assumenda aut quod corporis qui quia.\n\nExplicabo ad sunt nostrum natus aliquam omnis. Vel eos expedita omnis impedit itaque. Dolor similique illo beatae magnam quibusdam corporis.\n\nMollitia aut assumenda optio quae. Quae et voluptatibus ipsum debitis. Ducimus aperiam voluptas ab consequatur odio rerum aut ea.\n\nSunt aut voluptatum quibusdam magnam officia corporis qui. Facilis aut quia accusamus officia. Quo est accusamus explicabo sint et qui. Et et optio alias nobis voluptate.\n\nNemo voluptas sed reprehenderit assumenda molestiae. Fugit quidem dignissimos vitae sit fugiat eaque.', '2016-09-07 11:09:32', '2016-09-07 11:09:32', '2016-08-30 14:00:41');
INSERT INTO `posts` VALUES ('19', 'minus-dolorem-dolorem-voluptatem-consequatur-sint-dolore-nisi-aut-eum-molestiae', 'Minus dolorem dolorem voluptatem consequatur sint dolore nisi aut eum molestiae.', 'Repellat quibusdam incidunt doloribus totam ut accusamus consequatur quibusdam. Saepe sint sit quasi eligendi molestiae aut exercitationem. Sunt enim rerum est porro quisquam ut harum inventore. Ut qui ut odit in porro qui deserunt aut. Error error ab rerum sit consequuntur.\n\nProvident quos pariatur quod est nam sed. Necessitatibus at iusto ex et sunt. Quasi iusto non neque non aut. Voluptatibus debitis molestias ea tenetur laboriosam architecto veniam minus. Temporibus laborum quos molestiae vel eum.\n\nDucimus non et sed ullam. Voluptate consequuntur rem aut soluta nostrum deserunt mollitia. Possimus est voluptas distinctio officiis. Atque et non est quasi sit quia.\n\nTotam sit dolores provident architecto facere eum error. Fugiat unde nihil architecto ab ea suscipit quo adipisci. Optio voluptates amet ratione necessitatibus sed nemo modi.\n\nMagnam omnis molestiae autem dignissimos magni. Quia veritatis ut tempora accusamus tenetur enim rem. Molestiae et tempora id et. Voluptas rerum occaecati quis adipisci maiores alias dicta deserunt.\n\nPariatur voluptatem dignissimos id fugit quas sed. Et et non illum ut ratione. Aut laborum dolores doloribus ea. Ipsum iusto iure id est.', '2016-09-07 11:09:32', '2016-09-07 11:09:32', '2016-08-29 10:20:05');
INSERT INTO `posts` VALUES ('20', 'amet-aut-est-itaque-et-qui-quia-voluptate-eius-labore-eum-impedit', 'Amet aut est itaque et qui quia voluptate eius labore eum impedit.', 'Soluta maxime odio et aut maxime molestiae excepturi ipsa. Vel dignissimos ratione aut tenetur. Porro tempore in sapiente reprehenderit neque saepe incidunt. Mollitia est laborum neque natus.\n\nCorrupti necessitatibus tenetur molestias vel. Non magni in et incidunt officia beatae.\n\nEt consequatur et quis aut qui iusto eaque porro. Et tempora similique molestias qui. Minima earum repudiandae nam deleniti. Adipisci similique sit atque sed ratione enim sint.\n\nEnim reiciendis eos veritatis explicabo. Autem est suscipit magnam magni enim ea sunt. Neque maiores nostrum libero maiores eligendi eaque sapiente. Nam quisquam laborum distinctio sint autem officia quia omnis.\n\nArchitecto illum blanditiis illum veniam. Ea nihil consequatur ab repellat itaque quisquam voluptas. Omnis similique illum voluptates dolore. Molestiae earum necessitatibus nostrum maiores.', '2016-09-07 11:09:33', '2016-09-07 11:09:33', '2016-08-29 23:05:16');

-- ----------------------------
-- Table structure for users
-- ----------------------------
DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `email` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `password` varchar(60) COLLATE utf8_unicode_ci NOT NULL,
  `remember_token` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `updated_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`id`),
  UNIQUE KEY `users_email_unique` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- ----------------------------
-- Records of users
-- ----------------------------
SET FOREIGN_KEY_CHECKS=1;
